# Generated by Django 4.2.3 on 2023-09-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bannerarea_alter_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerarea',
            name='Link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
